services:
  - type: web
    name: django-backend
    env: python
    region: oregon
    branch: main
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn djob_backend.wsgi --log-file -"
    autoDeploy: true
    plan: free
